# Base image
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY send_email_api.py .

# Expose API port
EXPOSE 8000

# Command to run FastAPI
CMD ["uvicorn", "send_email_api:app", "--host", "0.0.0.0", "--port", "8000"]
